export const members = [
  {
    id: 1,
    name: 'Leanne',
    infix: '',
    lastName: 'Graham',
    companyName: 'Bret',
    jobTitle: 'Front-end developer',
    email: 'Sincere@april.biz',
  },
  {
    id: 2,
    name: 'Leanne',
    infix: '',
    lastName: 'Graham',
    companyName: 'Bret',
    jobTitle: 'Front-end developer',
    email: 'Sincere@april.biz',
  },
  {
    id: 3,
    name: 'Leanne',
    infix: '',
    lastName: 'Graham',
    companyName: 'Bret',
    jobTitle: 'Front-end developer',
    email: 'Sincere@april.biz',
  },
  {
    id: 4,
    name: 'Leanne',
    lastName: 'Graham',
    companyName: 'Bret',
    jobTitle: 'Front-end developer',
    email: 'Sincere@april.biz',
  },
  {
    id: 5,
    name: 'Leanne',
    lastName: 'Graham',
    companyName: 'Bret',
    jobTitle: 'Front-end developer',
    email: 'Sincere@april.biz',
  },
  {
    id: 6,
    name: 'Dennis ',
    lastName: 'Schulist',
    companyName: 'Bret',
    jobTitle: 'Front-end developer',
    email: 'Sincere@april.biz',
  },
  {
    id: 7,
    name: 'Kurtis',
    lastName: 'Weissnat',
    companyName: 'Bret',
    jobTitle: 'Front-end developer',
    email: 'Sincere@april.biz',
  },
  {
    id: 8,
    name: 'Nicholas',
    lastName: 'Runolfsdottir',
    companyName: 'Bret',
    jobTitle: 'Front-end developer',
    email: 'Sincere@april.biz',
  },
  {
    id: 9,
    name: 'Glenna',
    lastName: 'Reichert',
    companyName: 'Bret',
    jobTitle: 'Front-end developer',
    email: 'Sincere@april.biz',
  },
  {
    id: 10,
    name: 'Clementina',
    lastName: 'DuBuque',
    companyName: 'Bret',
    jobTitle: 'Front-end developer',
    email: 'Sincere@april.biz',
  }
];
